export const returnAppleHi = (nameStock) => {
  const name = nameStock.replace(/\s+/g, " ");
  return (
    name.indexOf("AirPods") != -1 ||
    name.indexOf("Airpods") != -1 ||
    name.indexOf("Air Pods") != -1 ||
    name.indexOf("Pencil") != -1 ||
    name.indexOf("HomePod") != -1 ||
    name.indexOf("Watch SE") != -1 ||
    name.indexOf("SE (2023) Gen") != -1 ||
    name.indexOf("SE 2") != -1 ||
    name.indexOf("SE2 4") != -1 ||
    name.indexOf("Se3") != -1 ||
    name.indexOf("SE 64") != -1 ||
    name.indexOf("SE 128") != -1 ||
    name.indexOf("SE 256") != -1 ||
    name.indexOf("11 64") != -1 ||
    name.indexOf("11 128") != -1 ||
    name.indexOf("12 Mini") != -1 ||
    name.indexOf("12 64") != -1 ||
    name.indexOf("12 128") != -1 ||
    name.indexOf("12 256") != -1 ||
    name.indexOf("12 Pro ") != -1 ||
    name.indexOf("12 Pro Max") != -1 ||
    name.indexOf("13 Mini") != -1 ||
    name.indexOf("13 128") != -1 ||
    name.indexOf("13 256") != -1 ||
    name.indexOf("13 512") != -1 ||
    name.indexOf("14 128") != -1 ||
    name.indexOf("14 256") != -1 ||
    name.indexOf("14 512") != -1 ||
    name.indexOf("14 Plus") != -1 ||
    name.indexOf("14 Pro 128") != -1 ||
    name.indexOf("14 Pro 256") != -1 ||
    name.indexOf("14 Pro 512") != -1 ||
    name.indexOf("14 Pro 1Tb") != -1 ||
    name.indexOf("14 Pro 1TB") != -1 ||
    name.indexOf("14 Pro Max") != -1 ||
    name.indexOf("15 128") != -1 ||
    name.indexOf("15 256") != -1 ||
    name.indexOf("15 512") != -1 ||
    name.indexOf("iPad 9") != -1 ||
    name.indexOf("iPad 10") != -1 ||
    name.indexOf("iPad Mini 6") != -1 ||
    name.indexOf("iPad Air 5") != -1 ||
    name.indexOf("iPad Pro") != -1 ||
    name.indexOf("PRO 12.9") != -1 ||
    name.indexOf("PRO 11") != -1 ||
    name.indexOf("AIR 11") != -1 ||
    name.indexOf("AIR 13") != -1 ||
    name.indexOf("AIR 5") != -1 ||
    name.indexOf("AW Series 9") != -1 ||
    name.indexOf("AW 9") != -1 ||
    name.indexOf("AW  9") != -1 ||
    name.indexOf("S 9 ") != -1 ||
    name.indexOf("AW Series 8") != -1 ||
    name.indexOf("AW 8") != -1 ||
    name.indexOf("AW  8") != -1 ||
    name.indexOf("S 8 ") != -1 ||
    name.indexOf("UL ") != -1 ||
    name.indexOf("Mac") != -1 ||
    name.indexOf("15 Plus 128") != -1 ||
    name.indexOf("15 Plus 256") != -1 ||
    name.indexOf("15 Plus 512") != -1 ||
    name.indexOf("15 Pro 128") != -1 ||
    name.indexOf("15 Pro 256") != -1 ||
    name.indexOf("15 Pro 512") != -1 ||
    name.indexOf("15 Pro 1Tb") != -1 ||
    name.indexOf("15 ProMax 256") != -1 ||
    name.indexOf("15 Pro Max 512") != -1 ||
    name.indexOf("15 Pro Max 256") != -1 ||
    name.indexOf("15 ProMax 512") != -1 ||
    name.indexOf("15 ProMax 1Tb") != -1 ||
    name.indexOf("15 Pro Max 1TB") != -1 ||
    name.indexOf("15 Pro Max 1Tb") != -1 ||
    name.indexOf("16 128") != -1 ||
    name.indexOf("16 256") != -1 ||
    name.indexOf("16 512") != -1 ||
    name.indexOf("16 Plus 128") != -1 ||
    name.indexOf("16 Plus 256") != -1 ||
    name.indexOf("16 Plus 512") != -1 ||
    name.indexOf("16 Pro 128") != -1 ||
    name.indexOf("16 Pro 256") != -1 ||
    name.indexOf("16 Pro 512") != -1 ||
    name.indexOf("16 Pro 1Tb") != -1 ||
    name.indexOf("16 ProMax 256") != -1 ||
    name.indexOf("16 ProMax 512") != -1 ||
    name.indexOf("16 ProMax 1Tb") != -1 ||
    name.indexOf("16 Pro Max 256") != -1 ||
    name.indexOf("16 Pro Max 512") != -1 ||
    name.indexOf("16 Pro Max 1Tb") != -1 ||
    name.indexOf("16 Pro Max 1TB") != -1 ||
    name.indexOf("16 Pro Max 1Tb") != -1 ||
    name.indexOf("iPad Pro 12.9") != -1 ||
    name.indexOf("Ultra 2") != -1 ||
    name.indexOf("Macbook") != -1 ||
    name.indexOf("Book ") != -1 ||
    name.indexOf("MB") != -1 ||
    name.indexOf("Vision Pro") != -1 ||
    name.indexOf("Watch S8") != -1 ||
    name.indexOf("Watch S9") != -1 ||
    name.indexOf("IPad 9") != -1 ||
    name.indexOf("Magic Keyboard") != -1 ||
    name.indexOf("MINI 6") != -1 ||
    name.indexOf("Air 13") != -1 ||
    name.indexOf("Air 15") != -1 ||
    name.indexOf("Pro 13") != -1 ||
    name.indexOf("Pro 15") != -1 ||
    name.indexOf("Pro 16") != -1 ||
    el.name.indexOf("MBPM2-03") != -1 ||
    el.name.indexOf("MBPM2-04") != -1 ||
    el.name.indexOf("MBPM2-05") != -1 ||
    el.name.indexOf("MBPM2-06") != -1 ||
    el.name.indexOf("MBPM2-07") != -1 ||
    el.name.indexOf("MBPM2-08") != -1 ||
    el.name.indexOf("MBPM2-09") != -1 ||
    el.name.indexOf("MBPM2-10") != -1 ||
    el.name.indexOf("MBPM2-11") != -1 ||
    el.name.indexOf("MBPM2-12") != -1 ||
    el.name.indexOf("MBPM2SL-03") != -1 ||
    el.name.indexOf("MBPM2SL-04") != -1 ||
    el.name.indexOf("MBPM2SL-05") != -1 ||
    el.name.indexOf("MBPM2SL-06") != -1 ||
    el.name.indexOf("MBPM2SL-07") != -1 ||
    el.name.indexOf("MBPM2SL-08") != -1 ||
    el.name.indexOf("MBPM2SL-09") != -1 ||
    el.name.indexOf("MBPM2SL-10") != -1 ||
    el.name.indexOf("MBPM2SL-11") != -1 ||
    el.name.indexOf("MBPM2SL-12") != -1 ||
    el.name.indexOf("MGN63") != -1 ||
    el.name.indexOf("MGN93") != -1 ||
    el.name.indexOf("MGND3") != -1 ||
    el.name.indexOf("MLXW3") != -1 ||
    el.name.indexOf("MLXX3") != -1 ||
    el.name.indexOf("MLXY3") != -1 ||
    el.name.indexOf("MLY03") != -1 ||
    el.name.indexOf("MLY13") != -1 ||
    el.name.indexOf("MLY23") != -1 ||
    el.name.indexOf("MLY33") != -1 ||
    el.name.indexOf("MLY43") != -1 ||
    el.name.indexOf("MNEH3") != -1 ||
    el.name.indexOf("MNEJ3") != -1 ||
    el.name.indexOf("MNEP3") != -1 ||
    el.name.indexOf("MNEQ3") != -1 ||
    el.name.indexOf("MPHE3") != -1 ||
    el.name.indexOf("MPHF3") != -1 ||
    el.name.indexOf("MPHH3") != -1 ||
    el.name.indexOf("MPHJ3") != -1 ||
    el.name.indexOf("MQKP3") != -1 ||
    el.name.indexOf("MQKQ3") != -1 ||
    el.name.indexOf("MQKR3") != -1 ||
    el.name.indexOf("MQKT3") != -1 ||
    el.name.indexOf("MQKU3") != -1 ||
    el.name.indexOf("MQKU3") != -1 ||
    el.name.indexOf("MQKV3") != -1 ||
    el.name.indexOf("MQKW3") != -1 ||
    el.name.indexOf("MQKX3") != -1 ||
    el.name.indexOf("MR7J3") != -1 ||
    el.name.indexOf("MR7K3") != -1 ||
    el.name.indexOf("MRW13") != -1 ||
    el.name.indexOf("MRW23") != -1 ||
    el.name.indexOf("MRW33") != -1 ||
    el.name.indexOf("MRW43") != -1 ||
    el.name.indexOf("MRW63") != -1 ||
    el.name.indexOf("MRW73") != -1 ||
    el.name.indexOf("MRX33") != -1 ||
    el.name.indexOf("MRX43") != -1 ||
    el.name.indexOf("MRX53") != -1 ||
    el.name.indexOf("MRX63") != -1 ||
    el.name.indexOf("MRX73") != -1 ||
    el.name.indexOf("MRX83") != -1 ||
    el.name.indexOf("MRXN3") != -1 ||
    el.name.indexOf("MRXP3") != -1 ||
    el.name.indexOf("MRXQ3") != -1 ||
    el.name.indexOf("MRXR3") != -1 ||
    el.name.indexOf("MRXT3") != -1 ||
    el.name.indexOf("MRXU3") != -1 ||
    el.name.indexOf("MRXV3") != -1 ||
    el.name.indexOf("MRXW3") != -1 ||
    el.name.indexOf("MRYM3") != -1 ||
    el.name.indexOf("MRYN3") != -1 ||
    el.name.indexOf("MRYP3") != -1 ||
    el.name.indexOf("MRYQ3") != -1 ||
    el.name.indexOf("MRYR3") != -1 ||
    el.name.indexOf("MRYT3") != -1 ||
    el.name.indexOf("MRYU3") != -1 ||
    el.name.indexOf("MRYV3") != -1 ||
    el.name.indexOf("MTL73") != -1 ||
    el.name.indexOf("MTL83") != -1 ||
    el.name.indexOf("MUW63") != -1 ||
    el.name.indexOf("MUW73") != -1 ||
    el.name.indexOf("MXCR3") != -1 ||
    el.name.indexOf("MXCT3") != -1 ||
    el.name.indexOf("MXCU3") != -1 ||
    el.name.indexOf("MXCV3") != -1 ||
    el.name.indexOf("MXD13") != -1 ||
    el.name.indexOf("MXD23") != -1 ||
    el.name.indexOf("MXD33") != -1 ||
    el.name.indexOf("MXD43") != -1 ||
    el.name.indexOf("Z1AW001FY") != -1 ||
    el.name.indexOf("Z1AW001LV") != -1 ||
    el.name.indexOf("Z1AW001NS") != -1 ||
    el.name.indexOf("MGNR3") != -1 ||
    el.name.indexOf("MGNT3") != -1 ||
    el.name.indexOf("MGPC3") != -1 ||
    el.name.indexOf("MGPD3") != -1 ||
    el.name.indexOf("MGPH3") != -1 ||
    el.name.indexOf("MGPJ3") != -1 ||
    el.name.indexOf("MGPK3") != -1 ||
    el.name.indexOf("MGPL3") != -1 ||
    el.name.indexOf("MGPM3") != -1 ||
    el.name.indexOf("MGPN3") != -1 ||
    el.name.indexOf("MGTF3") != -1 ||
    el.name.indexOf("MJV83") != -1 ||
    el.name.indexOf("MJV93") != -1 ||
    el.name.indexOf("MJVA3") != -1 ||
    el.name.indexOf("MQR93") != -1 ||
    el.name.indexOf("MQRA3") != -1 ||
    el.name.indexOf("MQRC3") != -1 ||
    el.name.indexOf("MQRD3") != -1 ||
    el.name.indexOf("MQRJ3") != -1 ||
    el.name.indexOf("MQRK3") != -1 ||
    el.name.indexOf("MQRN3") != -1 ||
    el.name.indexOf("MQRP3") != -1 ||
    el.name.indexOf("MQRQ3") != -1 ||
    el.name.indexOf("MQRR3") != -1 ||
    el.name.indexOf("MQRT3") != -1 ||
    el.name.indexOf("MQRU3") != -1 ||
    el.name.indexOf("MXNG2") != -1 ||
    el.name.indexOf("Z12SIMAC01") != -1 ||
    el.name.indexOf("Z12TIMAC01") != -1 ||
    el.name.indexOf("Z130IMAC01") != -1 ||
    el.name.indexOf("Z131IMAC01") != -1 ||
    el.name.indexOf("Z132IMAC01") != -1 ||
    el.name.indexOf("Z133IMAC01") != -1 ||
    el.name.indexOf("MXNF2") != -1
  );
};
